# Generated by Django 2.2.3 on 2019-12-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0006_sahil_temporarytbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Sahil',
        ),
        migrations.DeleteModel(
            name='Temporarytbl',
        ),
    ]
